services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fastapp:${FASTAPP_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      FASTAPP_HOST: 0.0.0.0


